### ISSUE TITLE
Control via VPN

### ISSUE THREAD

**Issue by lewko1** [cold-logic/heos-controller-electron#2]
I have a requirement to adjust the volume on speakers installed at a remote site where listeners cannot physically reach them.

I can connect to the site via VPN. The Heos 'app' won't work as it requires a WiFi connection and even connecting my phone via VPN doesn't work.

My reason for downloading this app is in the hope of being able to do this. It does not seem able to identify devices on a remote (VPN) network.

**Comment by cold-logic** [comment]
This is a cool use case. Unfortunately I'm not sure there is much I can do from within the code to allow this. The process of discovering the speakers involves sending out UDP packets to all of the nodes in your LAN but these multicast packets usually get dropped once they reach the edge of your network (i.e. your router/modem). In order to avoid that you'll need to configure your VPN to catch and route the SSDP multicast traffic from your LAN through the VPN and onto your client's LAN. Setting up the routing for this can be tricky and I'd have to know more about your specific configuration to be able to provide helpful instructions.

The stack overflow article below explains some of the technical details surrounding how to configure some routing rules for OpenVPN (assuming that's what your using) on both the vpn client (you) and the remote vpn server.

https://stackoverflow.com/questions/37032269/how-to-run-ssdp-upnp-discovery-through-openvpn

Hopefully this'll help get you on the right track. I'm pretty confident that if you can get your VPN setup correctly, you'll be able to discover the speakers and control them without issue.
